show_for_members:
  type: bool
  default: true
show_for_anon:
  type: bool
  default: false
display_on_mobile:
  type: bool
  default: true
display_on_desktop:
  type: bool
  default: true
display_on_homepage:
  type: bool
  default: false
url_must_contain:
  type: list
  list_type: simple
  default: /c/partners/49
dismissible:
  type: bool
  default: false
collapsible:
  type: bool
  default: true
default_collapsed_state:
  type: enum
  default: expanded
  choices:
    - expanded
    - collapsed
cookie_lifespan:
  type: enum
  default: none
  choices:
    - minute
    - day
    - week
    - month
    - year
cookie_name:
  type: string
  default: "v1"
full_width_banner:
  type: bool
  default: false
swap_default_positioning:
  type: bool
  default: false
plugin_outlet:
  type: enum
  default: "below-site-header"
  choices:
    - "below-site-header"
    - "above-main-container"
  refresh: true
banner_background_image:
  type: string
  default: ""
banner_background_image_dark:
  type: string
  default: ""
background_color:
  type: string
  default: "transparent"
background_color_dark:
  type: string
  default: ""
primary_text_color:
  type: string
  default: "#000"
primary_text_color_dark:
  type: string
  default: "#eaeaea"
secondary_text_color:
  type: string
  default: ""
secondary_text_color_dark:
  type: string
  default: ""
link_text_color:
  type: string
  default: "#0f82af"
link_text_color_dark:
  type: string
  default: ""
main_heading_content:
  type: string
  textarea: true
  default: |
    <h2 class="x-title">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    </h2>
    <div class="colored-line"></div>
    <div class="description">
      <p>
        Nulla ullamcorper augue vel sodales pellentesque. Sed
        vitae sapien sit amet mauris consequat malesuada.
        Vestibulum vitae iaculis nisl, vel aliquet velit.
        Fusce venenatis laoreet diam, non dictum nisl
        vestibulum non.
      </p>
    </div>
    <div class="colored-line"></div>
first_column_content:
  type: string
  textarea: true
  default: |
    <div class="card">
      <h2 class="banner-title">Vercel SHIP 2025 | NYC</h2>
      <p>
        Vercel SHIP is an in-person and virtual event bringing together Vercel customers, community members, partners, and media attendees to learn about Vercel’s latest product releases.
      </p>
      <p>
        Join us as an official sponsor or speak on the main stage <strong>June 24 / 25, 2025</strong> in <strong>New York City</strong>!
      </p>
      <div class="buttons" id="my-button">
        <a href="/t/about-the-drafts-category/148" class="btn btn-icon-text">More details</a>
      </div>
    </div>
second_column_content:
  type: string
  textarea: true
  default: |
    <div class="card">
      <h2 class="banner-title">"Shipped on Vercel"</h2>
      <p>
        We’re gearing up for a new brand campaign launching next month.
      </p>
      <p>
        We want the focus to be all about our customers, large and emerging, and share their websites and web apps across multiple mediums—landing pages, billboards, blogs, interviews, social.
      </p>
      <p>
        Let us know about your favorite customers or projects.
      </p>
      <div class="buttons" id="my-button">
        <a href="/t/this-is-a-draft-post/150/1" class="btn btn-icon-text">More details</a>
      </div>
    </div>
third_column_content:
  type: string
  textarea: true
  default: ""
fourth_column_content:
  type: string
  textarea: true
  default: ""
first_column_size:
  type: string
  default: "auto"
second_column_size:
  type: string
  default: "auto"
third_column_size:
  type: string
  default: ""
fourth_column_size:
  type: string
  default: ""
first_column_icon:
  type: string
  default: ""
second_column_icon:
  type: string
  default: ""
third_column_icon:
  type: string
  default: ""
fourth_column_icon:
  type: string
  default: ""
